# Generated by Django 4.1.3 on 2022-11-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0003_remove_investimento_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='investimento',
            field=models.TextField(max_length=25),
        ),
    ]
